# Header
menu:
  Home: /
  Archives: /archives
## rss: /atom.xml

# Content
excerpt_link: Read More...
fancybox: true

# Sidebar
sidebar: left
widgets:
- recent_posts
- category
- archive
- tagcloud
- weibo
##- blogroll

##- tag


# Miscellaneous
google_analytics:
favicon: /favicon.ico
twitter:
google_plus:
